name: Frontend build

# Controls when the workflow will run
on:
  pull_request:
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  web-deploy:
    name: Frontend build
    runs-on: ubuntu-latest
    steps:
    - name: Get latest version of code
      uses: actions/checkout@v2

    - name: Use Node.js 16
      uses: actions/setup-node@v2
      with:
        node-version: '16'
      
    - name: Build
      run: |
        yarn
        yarn build
      working-directory: ./frontend
      
