name: Build and deploy staging to google could storage
on:
  pull_request:
    branches: [ main ]
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./contracts
    strategy:
      matrix:
        node: [ 16 ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: Hardhat Solidity
      # You may pin to the exact commit or the version.
  # uses: amine7777/hardhat-action@6d4d1e7c02ea3920b9c1d45939c66c2379c42e1f
        uses: amine7777/hardhat-action@v1
        with:
    # Command to pass to hardhart
    # Path to another directory in the repository, where hardhat command will be issued from.
Useful in those cases where hardhat config is not in git repository root.
          working_dir: ./contracts
