# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2

    - name: Use Node.js 16
      uses: actions/setup-node@v2
      with:
        node-version: '16'
      
    - name: 🔨 Build Project
      run: |
        yarn
        yarn build
      working-directory: ./frontend
    
    - name: 📂 Upload files
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ftp.sharkdev.eu
        username: nipfi
        password: ${{ secrets.password }}
        local-dir: ./frontend/build/
        server-dir: ./
