# This is a basic workflow to help you get started with Actions

name: Frontend deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  web-deploy:
    name: Frontend deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get latest version of code
      uses: actions/checkout@v2

    - name: Use Node.js 16
      uses: actions/setup-node@v2
      with:
        node-version: '16'
      
    - name: Build
      run: |
        yarn
        yarn build
      working-directory: ./frontend
    
    - name: Deploy to server
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ftp.sharkdev.eu
        username: nipfi@sharkdev.eu
        password: ${{ secrets.password }}
        local-dir: ./frontend/build/
        server-dir: ./
